#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanManage.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Human")]
	public partial class HumanDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertcustomerTab(customerTab instance);
    partial void UpdatecustomerTab(customerTab instance);
    partial void DeletecustomerTab(customerTab instance);
    partial void InsertworkDesTab(workDesTab instance);
    partial void UpdateworkDesTab(workDesTab instance);
    partial void DeleteworkDesTab(workDesTab instance);
    partial void InsertdepartmentTab(departmentTab instance);
    partial void UpdatedepartmentTab(departmentTab instance);
    partial void DeletedepartmentTab(departmentTab instance);
    partial void InsertemployeeTab(employeeTab instance);
    partial void UpdateemployeeTab(employeeTab instance);
    partial void DeleteemployeeTab(employeeTab instance);
    partial void InsertjobBaseTab(jobBaseTab instance);
    partial void UpdatejobBaseTab(jobBaseTab instance);
    partial void DeletejobBaseTab(jobBaseTab instance);
    partial void InsertjobCfgTab(jobCfgTab instance);
    partial void UpdatejobCfgTab(jobCfgTab instance);
    partial void DeletejobCfgTab(jobCfgTab instance);
    partial void InsertpersonTab(personTab instance);
    partial void UpdatepersonTab(personTab instance);
    partial void DeletepersonTab(personTab instance);
    partial void InsertpublishJobTab(publishJobTab instance);
    partial void UpdatepublishJobTab(publishJobTab instance);
    partial void DeletepublishJobTab(publishJobTab instance);
    partial void InsertrightTab(rightTab instance);
    partial void UpdaterightTab(rightTab instance);
    partial void DeleterightTab(rightTab instance);
    partial void InserttaskTab(taskTab instance);
    partial void UpdatetaskTab(taskTab instance);
    partial void DeletetaskTab(taskTab instance);
    partial void InserttaskTmpTab(taskTmpTab instance);
    partial void UpdatetaskTmpTab(taskTmpTab instance);
    partial void DeletetaskTmpTab(taskTmpTab instance);
    #endregion
		
		public HumanDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HumanConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HumanDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HumanDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HumanDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HumanDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<customerTab> customerTabs
		{
			get
			{
				return this.GetTable<customerTab>();
			}
		}
		
		public System.Data.Linq.Table<workDesTab> workDesTabs
		{
			get
			{
				return this.GetTable<workDesTab>();
			}
		}
		
		public System.Data.Linq.Table<departmentTab> departmentTabs
		{
			get
			{
				return this.GetTable<departmentTab>();
			}
		}
		
		public System.Data.Linq.Table<employeeTab> employeeTabs
		{
			get
			{
				return this.GetTable<employeeTab>();
			}
		}
		
		public System.Data.Linq.Table<jobBaseTab> jobBaseTabs
		{
			get
			{
				return this.GetTable<jobBaseTab>();
			}
		}
		
		public System.Data.Linq.Table<jobCfgTab> jobCfgTabs
		{
			get
			{
				return this.GetTable<jobCfgTab>();
			}
		}
		
		public System.Data.Linq.Table<personTab> personTabs
		{
			get
			{
				return this.GetTable<personTab>();
			}
		}
		
		public System.Data.Linq.Table<publishJobTab> publishJobTabs
		{
			get
			{
				return this.GetTable<publishJobTab>();
			}
		}
		
		public System.Data.Linq.Table<rightTab> rightTabs
		{
			get
			{
				return this.GetTable<rightTab>();
			}
		}
		
		public System.Data.Linq.Table<taskTab> taskTabs
		{
			get
			{
				return this.GetTable<taskTab>();
			}
		}
		
		public System.Data.Linq.Table<taskTmpTab> taskTmpTabs
		{
			get
			{
				return this.GetTable<taskTmpTab>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.customerTab")]
	public partial class customerTab : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _C_RID;
		
		private System.Nullable<int> _ID;
		
		private System.Nullable<System.DateTime> _Name;
		
		private System.Nullable<System.DateTime> _Type;
		
		private System.Nullable<int> _City;
		
		private string _Industry;
		
		private string _Linkman;
		
		private string _Phone;
		
		private string _Email;
		
		private string _Source;
		
		private string _State;
		
		private string _Pay;
		
		private string _Communication;
		
		private string _Import_Emp_ID;
		
		private string _Import_Time;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnC_RIDChanging(int value);
    partial void OnC_RIDChanged();
    partial void OnIDChanging(System.Nullable<int> value);
    partial void OnIDChanged();
    partial void OnNameChanging(System.Nullable<System.DateTime> value);
    partial void OnNameChanged();
    partial void OnTypeChanging(System.Nullable<System.DateTime> value);
    partial void OnTypeChanged();
    partial void OnCityChanging(System.Nullable<int> value);
    partial void OnCityChanged();
    partial void OnIndustryChanging(string value);
    partial void OnIndustryChanged();
    partial void OnLinkmanChanging(string value);
    partial void OnLinkmanChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSourceChanging(string value);
    partial void OnSourceChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnPayChanging(string value);
    partial void OnPayChanged();
    partial void OnCommunicationChanging(string value);
    partial void OnCommunicationChanged();
    partial void OnImport_Emp_IDChanging(string value);
    partial void OnImport_Emp_IDChanged();
    partial void OnImport_TimeChanging(string value);
    partial void OnImport_TimeChanged();
    #endregion
		
		public customerTab()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_RID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int C_RID
		{
			get
			{
				return this._C_RID;
			}
			set
			{
				if ((this._C_RID != value))
				{
					this.OnC_RIDChanging(value);
					this.SendPropertyChanging();
					this._C_RID = value;
					this.SendPropertyChanged("C_RID");
					this.OnC_RIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="DateTime")]
		public System.Nullable<System.DateTime> Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="DateTime")]
		public System.Nullable<System.DateTime> Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="Int")]
		public System.Nullable<int> City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Industry", DbType="NVarChar(50)")]
		public string Industry
		{
			get
			{
				return this._Industry;
			}
			set
			{
				if ((this._Industry != value))
				{
					this.OnIndustryChanging(value);
					this.SendPropertyChanging();
					this._Industry = value;
					this.SendPropertyChanged("Industry");
					this.OnIndustryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Linkman", DbType="NVarChar(50)")]
		public string Linkman
		{
			get
			{
				return this._Linkman;
			}
			set
			{
				if ((this._Linkman != value))
				{
					this.OnLinkmanChanging(value);
					this.SendPropertyChanging();
					this._Linkman = value;
					this.SendPropertyChanged("Linkman");
					this.OnLinkmanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NChar(10)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NChar(10)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Source", DbType="NChar(10)")]
		public string Source
		{
			get
			{
				return this._Source;
			}
			set
			{
				if ((this._Source != value))
				{
					this.OnSourceChanging(value);
					this.SendPropertyChanging();
					this._Source = value;
					this.SendPropertyChanged("Source");
					this.OnSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NChar(10)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pay", DbType="NChar(10)")]
		public string Pay
		{
			get
			{
				return this._Pay;
			}
			set
			{
				if ((this._Pay != value))
				{
					this.OnPayChanging(value);
					this.SendPropertyChanging();
					this._Pay = value;
					this.SendPropertyChanged("Pay");
					this.OnPayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Communication", DbType="NChar(10)")]
		public string Communication
		{
			get
			{
				return this._Communication;
			}
			set
			{
				if ((this._Communication != value))
				{
					this.OnCommunicationChanging(value);
					this.SendPropertyChanging();
					this._Communication = value;
					this.SendPropertyChanged("Communication");
					this.OnCommunicationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Import_Emp_ID", DbType="NChar(10)")]
		public string Import_Emp_ID
		{
			get
			{
				return this._Import_Emp_ID;
			}
			set
			{
				if ((this._Import_Emp_ID != value))
				{
					this.OnImport_Emp_IDChanging(value);
					this.SendPropertyChanging();
					this._Import_Emp_ID = value;
					this.SendPropertyChanged("Import_Emp_ID");
					this.OnImport_Emp_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Import_Time", DbType="NChar(10)")]
		public string Import_Time
		{
			get
			{
				return this._Import_Time;
			}
			set
			{
				if ((this._Import_Time != value))
				{
					this.OnImport_TimeChanging(value);
					this.SendPropertyChanging();
					this._Import_Time = value;
					this.SendPropertyChanged("Import_Time");
					this.OnImport_TimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.workDesTab")]
	public partial class workDesTab : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _WD_RID;
		
		private System.Nullable<int> _P_ID;
		
		private System.Nullable<System.DateTime> _Start_Time;
		
		private System.Nullable<System.DateTime> _End_Time;
		
		private System.Nullable<int> _Job;
		
		private string _Department;
		
		private string _Description;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWD_RIDChanging(int value);
    partial void OnWD_RIDChanged();
    partial void OnP_IDChanging(System.Nullable<int> value);
    partial void OnP_IDChanged();
    partial void OnStart_TimeChanging(System.Nullable<System.DateTime> value);
    partial void OnStart_TimeChanged();
    partial void OnEnd_TimeChanging(System.Nullable<System.DateTime> value);
    partial void OnEnd_TimeChanged();
    partial void OnJobChanging(System.Nullable<int> value);
    partial void OnJobChanged();
    partial void OnDepartmentChanging(string value);
    partial void OnDepartmentChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public workDesTab()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WD_RID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int WD_RID
		{
			get
			{
				return this._WD_RID;
			}
			set
			{
				if ((this._WD_RID != value))
				{
					this.OnWD_RIDChanging(value);
					this.SendPropertyChanging();
					this._WD_RID = value;
					this.SendPropertyChanged("WD_RID");
					this.OnWD_RIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_ID", DbType="Int")]
		public System.Nullable<int> P_ID
		{
			get
			{
				return this._P_ID;
			}
			set
			{
				if ((this._P_ID != value))
				{
					this.OnP_IDChanging(value);
					this.SendPropertyChanging();
					this._P_ID = value;
					this.SendPropertyChanged("P_ID");
					this.OnP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Start_Time", DbType="DateTime")]
		public System.Nullable<System.DateTime> Start_Time
		{
			get
			{
				return this._Start_Time;
			}
			set
			{
				if ((this._Start_Time != value))
				{
					this.OnStart_TimeChanging(value);
					this.SendPropertyChanging();
					this._Start_Time = value;
					this.SendPropertyChanged("Start_Time");
					this.OnStart_TimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_End_Time", DbType="DateTime")]
		public System.Nullable<System.DateTime> End_Time
		{
			get
			{
				return this._End_Time;
			}
			set
			{
				if ((this._End_Time != value))
				{
					this.OnEnd_TimeChanging(value);
					this.SendPropertyChanging();
					this._End_Time = value;
					this.SendPropertyChanged("End_Time");
					this.OnEnd_TimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Job", DbType="Int")]
		public System.Nullable<int> Job
		{
			get
			{
				return this._Job;
			}
			set
			{
				if ((this._Job != value))
				{
					this.OnJobChanging(value);
					this.SendPropertyChanging();
					this._Job = value;
					this.SendPropertyChanged("Job");
					this.OnJobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="NVarChar(50)")]
		public string Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this.OnDepartmentChanging(value);
					this.SendPropertyChanging();
					this._Department = value;
					this.SendPropertyChanged("Department");
					this.OnDepartmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(50)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.departmentTab")]
	public partial class departmentTab : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _D_RID;
		
		private System.Nullable<decimal> _ID;
		
		private string _Name;
		
		private System.Data.Linq.Binary _Right;
		
		private string _employees;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnD_RIDChanging(int value);
    partial void OnD_RIDChanged();
    partial void OnIDChanging(System.Nullable<decimal> value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnRightChanging(System.Data.Linq.Binary value);
    partial void OnRightChanged();
    partial void OnemployeesChanging(string value);
    partial void OnemployeesChanged();
    #endregion
		
		public departmentTab()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_RID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int D_RID
		{
			get
			{
				return this._D_RID;
			}
			set
			{
				if ((this._D_RID != value))
				{
					this.OnD_RIDChanging(value);
					this.SendPropertyChanging();
					this._D_RID = value;
					this.SendPropertyChanged("D_RID");
					this.OnD_RIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(8,0)")]
		public System.Nullable<decimal> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Right]", Storage="_Right", DbType="Binary(50)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Right
		{
			get
			{
				return this._Right;
			}
			set
			{
				if ((this._Right != value))
				{
					this.OnRightChanging(value);
					this.SendPropertyChanging();
					this._Right = value;
					this.SendPropertyChanged("Right");
					this.OnRightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employees", DbType="NChar(10)")]
		public string employees
		{
			get
			{
				return this._employees;
			}
			set
			{
				if ((this._employees != value))
				{
					this.OnemployeesChanging(value);
					this.SendPropertyChanging();
					this._employees = value;
					this.SendPropertyChanged("employees");
					this.OnemployeesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.employeeTab")]
	public partial class employeeTab : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _E_RID;
		
		private string _ID;
		
		private string _Name;
		
		private System.Nullable<int> _Age;
		
		private System.Nullable<bool> _Sex;
		
		private System.Nullable<decimal> _Phone;
		
		private string _Email;
		
		private string _Department;
		
		private string _Job;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnE_RIDChanging(int value);
    partial void OnE_RIDChanged();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAgeChanging(System.Nullable<int> value);
    partial void OnAgeChanged();
    partial void OnSexChanging(System.Nullable<bool> value);
    partial void OnSexChanged();
    partial void OnPhoneChanging(System.Nullable<decimal> value);
    partial void OnPhoneChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDepartmentChanging(string value);
    partial void OnDepartmentChanged();
    partial void OnJobChanging(string value);
    partial void OnJobChanged();
    #endregion
		
		public employeeTab()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_RID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int E_RID
		{
			get
			{
				return this._E_RID;
			}
			set
			{
				if ((this._E_RID != value))
				{
					this.OnE_RIDChanging(value);
					this.SendPropertyChanging();
					this._E_RID = value;
					this.SendPropertyChanged("E_RID");
					this.OnE_RIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NVarChar(50)")]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int")]
		public System.Nullable<int> Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this.OnAgeChanging(value);
					this.SendPropertyChanging();
					this._Age = value;
					this.SendPropertyChanged("Age");
					this.OnAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="Bit")]
		public System.Nullable<bool> Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this.OnSexChanging(value);
					this.SendPropertyChanging();
					this._Sex = value;
					this.SendPropertyChanged("Sex");
					this.OnSexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="Decimal(11,0)")]
		public System.Nullable<decimal> Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="NVarChar(50)")]
		public string Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this.OnDepartmentChanging(value);
					this.SendPropertyChanging();
					this._Department = value;
					this.SendPropertyChanged("Department");
					this.OnDepartmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Job", DbType="NVarChar(50)")]
		public string Job
		{
			get
			{
				return this._Job;
			}
			set
			{
				if ((this._Job != value))
				{
					this.OnJobChanging(value);
					this.SendPropertyChanging();
					this._Job = value;
					this.SendPropertyChanged("Job");
					this.OnJobChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.jobBaseTab")]
	public partial class jobBaseTab : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _J_RID;
		
		private System.Nullable<decimal> _ID;
		
		private string _Name;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnJ_RIDChanging(int value);
    partial void OnJ_RIDChanged();
    partial void OnIDChanging(System.Nullable<decimal> value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public jobBaseTab()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_J_RID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int J_RID
		{
			get
			{
				return this._J_RID;
			}
			set
			{
				if ((this._J_RID != value))
				{
					this.OnJ_RIDChanging(value);
					this.SendPropertyChanging();
					this._J_RID = value;
					this.SendPropertyChanged("J_RID");
					this.OnJ_RIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(8,0)")]
		public System.Nullable<decimal> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.jobCfgTab")]
	public partial class jobCfgTab : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _JC_RID;
		
		private System.Nullable<decimal> _J_RID;
		
		private string _Right;
		
		private string _Department;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnJC_RIDChanging(int value);
    partial void OnJC_RIDChanged();
    partial void OnJ_RIDChanging(System.Nullable<decimal> value);
    partial void OnJ_RIDChanged();
    partial void OnRightChanging(string value);
    partial void OnRightChanged();
    partial void OnDepartmentChanging(string value);
    partial void OnDepartmentChanged();
    #endregion
		
		public jobCfgTab()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JC_RID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int JC_RID
		{
			get
			{
				return this._JC_RID;
			}
			set
			{
				if ((this._JC_RID != value))
				{
					this.OnJC_RIDChanging(value);
					this.SendPropertyChanging();
					this._JC_RID = value;
					this.SendPropertyChanged("JC_RID");
					this.OnJC_RIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_J_RID", DbType="Decimal(8,0)")]
		public System.Nullable<decimal> J_RID
		{
			get
			{
				return this._J_RID;
			}
			set
			{
				if ((this._J_RID != value))
				{
					this.OnJ_RIDChanging(value);
					this.SendPropertyChanging();
					this._J_RID = value;
					this.SendPropertyChanged("J_RID");
					this.OnJ_RIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Right]", Storage="_Right", DbType="NVarChar(50)")]
		public string Right
		{
			get
			{
				return this._Right;
			}
			set
			{
				if ((this._Right != value))
				{
					this.OnRightChanging(value);
					this.SendPropertyChanging();
					this._Right = value;
					this.SendPropertyChanged("Right");
					this.OnRightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="NVarChar(50)")]
		public string Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this.OnDepartmentChanging(value);
					this.SendPropertyChanging();
					this._Department = value;
					this.SendPropertyChanged("Department");
					this.OnDepartmentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.personTab")]
	public partial class personTab : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _P_RID;
		
		private System.Nullable<decimal> _ID;
		
		private string _Name;
		
		private System.Nullable<bool> _Sex;
		
		private System.Nullable<int> _Age;
		
		private string _Card;
		
		private string _CardType;
		
		private string _Education;
		
		private string _Job;
		
		private string _Industry;
		
		private System.Nullable<int> _Experience;
		
		private System.Nullable<decimal> _Money;
		
		private string _City;
		
		private System.Nullable<decimal> _Phone;
		
		private string _Email;
		
		private System.Nullable<decimal> _QQ;
		
		private string _State;
		
		private System.Nullable<int> _Import_EMP_ID;
		
		private System.Nullable<System.DateTime> _Import_Time;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnP_RIDChanging(int value);
    partial void OnP_RIDChanged();
    partial void OnIDChanging(System.Nullable<decimal> value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnSexChanging(System.Nullable<bool> value);
    partial void OnSexChanged();
    partial void OnAgeChanging(System.Nullable<int> value);
    partial void OnAgeChanged();
    partial void OnCardChanging(string value);
    partial void OnCardChanged();
    partial void OnCardTypeChanging(string value);
    partial void OnCardTypeChanged();
    partial void OnEducationChanging(string value);
    partial void OnEducationChanged();
    partial void OnJobChanging(string value);
    partial void OnJobChanged();
    partial void OnIndustryChanging(string value);
    partial void OnIndustryChanged();
    partial void OnExperienceChanging(System.Nullable<int> value);
    partial void OnExperienceChanged();
    partial void OnMoneyChanging(System.Nullable<decimal> value);
    partial void OnMoneyChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnPhoneChanging(System.Nullable<decimal> value);
    partial void OnPhoneChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnQQChanging(System.Nullable<decimal> value);
    partial void OnQQChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnImport_EMP_IDChanging(System.Nullable<int> value);
    partial void OnImport_EMP_IDChanged();
    partial void OnImport_TimeChanging(System.Nullable<System.DateTime> value);
    partial void OnImport_TimeChanged();
    #endregion
		
		public personTab()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_RID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int P_RID
		{
			get
			{
				return this._P_RID;
			}
			set
			{
				if ((this._P_RID != value))
				{
					this.OnP_RIDChanging(value);
					this.SendPropertyChanging();
					this._P_RID = value;
					this.SendPropertyChanged("P_RID");
					this.OnP_RIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(8,0)")]
		public System.Nullable<decimal> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="Bit")]
		public System.Nullable<bool> Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this.OnSexChanging(value);
					this.SendPropertyChanging();
					this._Sex = value;
					this.SendPropertyChanged("Sex");
					this.OnSexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int")]
		public System.Nullable<int> Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this.OnAgeChanging(value);
					this.SendPropertyChanging();
					this._Age = value;
					this.SendPropertyChanged("Age");
					this.OnAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Card", DbType="NVarChar(50)")]
		public string Card
		{
			get
			{
				return this._Card;
			}
			set
			{
				if ((this._Card != value))
				{
					this.OnCardChanging(value);
					this.SendPropertyChanging();
					this._Card = value;
					this.SendPropertyChanged("Card");
					this.OnCardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardType", DbType="NChar(10)")]
		public string CardType
		{
			get
			{
				return this._CardType;
			}
			set
			{
				if ((this._CardType != value))
				{
					this.OnCardTypeChanging(value);
					this.SendPropertyChanging();
					this._CardType = value;
					this.SendPropertyChanged("CardType");
					this.OnCardTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Education", DbType="NChar(10)")]
		public string Education
		{
			get
			{
				return this._Education;
			}
			set
			{
				if ((this._Education != value))
				{
					this.OnEducationChanging(value);
					this.SendPropertyChanging();
					this._Education = value;
					this.SendPropertyChanged("Education");
					this.OnEducationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Job", DbType="NVarChar(50)")]
		public string Job
		{
			get
			{
				return this._Job;
			}
			set
			{
				if ((this._Job != value))
				{
					this.OnJobChanging(value);
					this.SendPropertyChanging();
					this._Job = value;
					this.SendPropertyChanged("Job");
					this.OnJobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Industry", DbType="NVarChar(50)")]
		public string Industry
		{
			get
			{
				return this._Industry;
			}
			set
			{
				if ((this._Industry != value))
				{
					this.OnIndustryChanging(value);
					this.SendPropertyChanging();
					this._Industry = value;
					this.SendPropertyChanged("Industry");
					this.OnIndustryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Experience", DbType="Int")]
		public System.Nullable<int> Experience
		{
			get
			{
				return this._Experience;
			}
			set
			{
				if ((this._Experience != value))
				{
					this.OnExperienceChanging(value);
					this.SendPropertyChanging();
					this._Experience = value;
					this.SendPropertyChanged("Experience");
					this.OnExperienceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Money", DbType="Money")]
		public System.Nullable<decimal> Money
		{
			get
			{
				return this._Money;
			}
			set
			{
				if ((this._Money != value))
				{
					this.OnMoneyChanging(value);
					this.SendPropertyChanging();
					this._Money = value;
					this.SendPropertyChanged("Money");
					this.OnMoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NChar(10)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="Decimal(11,0)")]
		public System.Nullable<decimal> Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QQ", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> QQ
		{
			get
			{
				return this._QQ;
			}
			set
			{
				if ((this._QQ != value))
				{
					this.OnQQChanging(value);
					this.SendPropertyChanging();
					this._QQ = value;
					this.SendPropertyChanged("QQ");
					this.OnQQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NVarChar(50)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Import_EMP_ID", DbType="Int")]
		public System.Nullable<int> Import_EMP_ID
		{
			get
			{
				return this._Import_EMP_ID;
			}
			set
			{
				if ((this._Import_EMP_ID != value))
				{
					this.OnImport_EMP_IDChanging(value);
					this.SendPropertyChanging();
					this._Import_EMP_ID = value;
					this.SendPropertyChanged("Import_EMP_ID");
					this.OnImport_EMP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Import_Time", DbType="DateTime")]
		public System.Nullable<System.DateTime> Import_Time
		{
			get
			{
				return this._Import_Time;
			}
			set
			{
				if ((this._Import_Time != value))
				{
					this.OnImport_TimeChanging(value);
					this.SendPropertyChanging();
					this._Import_Time = value;
					this.SendPropertyChanged("Import_Time");
					this.OnImport_TimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.publishJobTab")]
	public partial class publishJobTab : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PJ_RID;
		
		private System.Nullable<int> _C_ID;
		
		private System.Nullable<System.DateTime> _Job;
		
		private System.Nullable<System.DateTime> _Description;
		
		private System.Nullable<int> _Money;
		
		private string _Industry;
		
		private string _Count;
		
		private string _Remain;
		
		private string _Person_ID;
		
		private string _SignDate;
		
		private string _Recommend_Emp_ID;
		
		private string _Cmp_Emp_ID;
		
		private string _Pay;
		
		private string _Import_Emp_ID;
		
		private string _Import_Time;
		
		private string _State;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPJ_RIDChanging(int value);
    partial void OnPJ_RIDChanged();
    partial void OnC_IDChanging(System.Nullable<int> value);
    partial void OnC_IDChanged();
    partial void OnJobChanging(System.Nullable<System.DateTime> value);
    partial void OnJobChanged();
    partial void OnDescriptionChanging(System.Nullable<System.DateTime> value);
    partial void OnDescriptionChanged();
    partial void OnMoneyChanging(System.Nullable<int> value);
    partial void OnMoneyChanged();
    partial void OnIndustryChanging(string value);
    partial void OnIndustryChanged();
    partial void OnCountChanging(string value);
    partial void OnCountChanged();
    partial void OnRemainChanging(string value);
    partial void OnRemainChanged();
    partial void OnPerson_IDChanging(string value);
    partial void OnPerson_IDChanged();
    partial void OnSignDateChanging(string value);
    partial void OnSignDateChanged();
    partial void OnRecommend_Emp_IDChanging(string value);
    partial void OnRecommend_Emp_IDChanged();
    partial void OnCmp_Emp_IDChanging(string value);
    partial void OnCmp_Emp_IDChanged();
    partial void OnPayChanging(string value);
    partial void OnPayChanged();
    partial void OnImport_Emp_IDChanging(string value);
    partial void OnImport_Emp_IDChanged();
    partial void OnImport_TimeChanging(string value);
    partial void OnImport_TimeChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    #endregion
		
		public publishJobTab()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PJ_RID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PJ_RID
		{
			get
			{
				return this._PJ_RID;
			}
			set
			{
				if ((this._PJ_RID != value))
				{
					this.OnPJ_RIDChanging(value);
					this.SendPropertyChanging();
					this._PJ_RID = value;
					this.SendPropertyChanged("PJ_RID");
					this.OnPJ_RIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_ID", DbType="Int")]
		public System.Nullable<int> C_ID
		{
			get
			{
				return this._C_ID;
			}
			set
			{
				if ((this._C_ID != value))
				{
					this.OnC_IDChanging(value);
					this.SendPropertyChanging();
					this._C_ID = value;
					this.SendPropertyChanged("C_ID");
					this.OnC_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Job", DbType="DateTime")]
		public System.Nullable<System.DateTime> Job
		{
			get
			{
				return this._Job;
			}
			set
			{
				if ((this._Job != value))
				{
					this.OnJobChanging(value);
					this.SendPropertyChanging();
					this._Job = value;
					this.SendPropertyChanged("Job");
					this.OnJobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="DateTime")]
		public System.Nullable<System.DateTime> Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Money", DbType="Int")]
		public System.Nullable<int> Money
		{
			get
			{
				return this._Money;
			}
			set
			{
				if ((this._Money != value))
				{
					this.OnMoneyChanging(value);
					this.SendPropertyChanging();
					this._Money = value;
					this.SendPropertyChanged("Money");
					this.OnMoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Industry", DbType="NVarChar(50)")]
		public string Industry
		{
			get
			{
				return this._Industry;
			}
			set
			{
				if ((this._Industry != value))
				{
					this.OnIndustryChanging(value);
					this.SendPropertyChanging();
					this._Industry = value;
					this.SendPropertyChanged("Industry");
					this.OnIndustryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Count", DbType="NVarChar(50)")]
		public string Count
		{
			get
			{
				return this._Count;
			}
			set
			{
				if ((this._Count != value))
				{
					this.OnCountChanging(value);
					this.SendPropertyChanging();
					this._Count = value;
					this.SendPropertyChanged("Count");
					this.OnCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remain", DbType="NChar(10)")]
		public string Remain
		{
			get
			{
				return this._Remain;
			}
			set
			{
				if ((this._Remain != value))
				{
					this.OnRemainChanging(value);
					this.SendPropertyChanging();
					this._Remain = value;
					this.SendPropertyChanged("Remain");
					this.OnRemainChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Person_ID", DbType="NChar(10)")]
		public string Person_ID
		{
			get
			{
				return this._Person_ID;
			}
			set
			{
				if ((this._Person_ID != value))
				{
					this.OnPerson_IDChanging(value);
					this.SendPropertyChanging();
					this._Person_ID = value;
					this.SendPropertyChanged("Person_ID");
					this.OnPerson_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SignDate", DbType="NChar(10)")]
		public string SignDate
		{
			get
			{
				return this._SignDate;
			}
			set
			{
				if ((this._SignDate != value))
				{
					this.OnSignDateChanging(value);
					this.SendPropertyChanging();
					this._SignDate = value;
					this.SendPropertyChanged("SignDate");
					this.OnSignDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Recommend_Emp_ID", DbType="NChar(10)")]
		public string Recommend_Emp_ID
		{
			get
			{
				return this._Recommend_Emp_ID;
			}
			set
			{
				if ((this._Recommend_Emp_ID != value))
				{
					this.OnRecommend_Emp_IDChanging(value);
					this.SendPropertyChanging();
					this._Recommend_Emp_ID = value;
					this.SendPropertyChanged("Recommend_Emp_ID");
					this.OnRecommend_Emp_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cmp_Emp_ID", DbType="NChar(10)")]
		public string Cmp_Emp_ID
		{
			get
			{
				return this._Cmp_Emp_ID;
			}
			set
			{
				if ((this._Cmp_Emp_ID != value))
				{
					this.OnCmp_Emp_IDChanging(value);
					this.SendPropertyChanging();
					this._Cmp_Emp_ID = value;
					this.SendPropertyChanged("Cmp_Emp_ID");
					this.OnCmp_Emp_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pay", DbType="NChar(10)")]
		public string Pay
		{
			get
			{
				return this._Pay;
			}
			set
			{
				if ((this._Pay != value))
				{
					this.OnPayChanging(value);
					this.SendPropertyChanging();
					this._Pay = value;
					this.SendPropertyChanged("Pay");
					this.OnPayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Import_Emp_ID", DbType="NChar(10)")]
		public string Import_Emp_ID
		{
			get
			{
				return this._Import_Emp_ID;
			}
			set
			{
				if ((this._Import_Emp_ID != value))
				{
					this.OnImport_Emp_IDChanging(value);
					this.SendPropertyChanging();
					this._Import_Emp_ID = value;
					this.SendPropertyChanged("Import_Emp_ID");
					this.OnImport_Emp_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Import_Time", DbType="NChar(10)")]
		public string Import_Time
		{
			get
			{
				return this._Import_Time;
			}
			set
			{
				if ((this._Import_Time != value))
				{
					this.OnImport_TimeChanging(value);
					this.SendPropertyChanging();
					this._Import_Time = value;
					this.SendPropertyChanged("Import_Time");
					this.OnImport_TimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NChar(10)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.rightTab")]
	public partial class rightTab : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _R_RID;
		
		private System.Nullable<decimal> _ID;
		
		private string _Name;
		
		private System.Nullable<int> _Level;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnR_RIDChanging(int value);
    partial void OnR_RIDChanged();
    partial void OnIDChanging(System.Nullable<decimal> value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnLevelChanging(System.Nullable<int> value);
    partial void OnLevelChanged();
    #endregion
		
		public rightTab()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_RID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int R_RID
		{
			get
			{
				return this._R_RID;
			}
			set
			{
				if ((this._R_RID != value))
				{
					this.OnR_RIDChanging(value);
					this.SendPropertyChanging();
					this._R_RID = value;
					this.SendPropertyChanged("R_RID");
					this.OnR_RIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(8,0)")]
		public System.Nullable<decimal> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level]", Storage="_Level", DbType="Int")]
		public System.Nullable<int> Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this.OnLevelChanging(value);
					this.SendPropertyChanging();
					this._Level = value;
					this.SendPropertyChanged("Level");
					this.OnLevelChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.taskTab")]
	public partial class taskTab : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _T_RID;
		
		private System.Nullable<decimal> _ID;
		
		private System.Nullable<int> _E_ID_Recv;
		
		private System.Nullable<int> _E_ID_Sent;
		
		private System.Nullable<System.DateTime> _CreateTime;
		
		private System.Nullable<System.DateTime> _EndTime;
		
		private System.Nullable<System.DateTime> _LimitTime;
		
		private string _Context;
		
		private string _Reback;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnT_RIDChanging(int value);
    partial void OnT_RIDChanged();
    partial void OnIDChanging(System.Nullable<decimal> value);
    partial void OnIDChanged();
    partial void OnE_ID_RecvChanging(System.Nullable<int> value);
    partial void OnE_ID_RecvChanged();
    partial void OnE_ID_SentChanging(System.Nullable<int> value);
    partial void OnE_ID_SentChanged();
    partial void OnCreateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateTimeChanged();
    partial void OnEndTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnEndTimeChanged();
    partial void OnLimitTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnLimitTimeChanged();
    partial void OnContextChanging(string value);
    partial void OnContextChanged();
    partial void OnRebackChanging(string value);
    partial void OnRebackChanged();
    #endregion
		
		public taskTab()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_RID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int T_RID
		{
			get
			{
				return this._T_RID;
			}
			set
			{
				if ((this._T_RID != value))
				{
					this.OnT_RIDChanging(value);
					this.SendPropertyChanging();
					this._T_RID = value;
					this.SendPropertyChanged("T_RID");
					this.OnT_RIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(8,0)")]
		public System.Nullable<decimal> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_ID_Recv", DbType="Int")]
		public System.Nullable<int> E_ID_Recv
		{
			get
			{
				return this._E_ID_Recv;
			}
			set
			{
				if ((this._E_ID_Recv != value))
				{
					this.OnE_ID_RecvChanging(value);
					this.SendPropertyChanging();
					this._E_ID_Recv = value;
					this.SendPropertyChanged("E_ID_Recv");
					this.OnE_ID_RecvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_ID_Sent", DbType="Int")]
		public System.Nullable<int> E_ID_Sent
		{
			get
			{
				return this._E_ID_Sent;
			}
			set
			{
				if ((this._E_ID_Sent != value))
				{
					this.OnE_ID_SentChanging(value);
					this.SendPropertyChanging();
					this._E_ID_Sent = value;
					this.SendPropertyChanged("E_ID_Sent");
					this.OnE_ID_SentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateTime
		{
			get
			{
				return this._CreateTime;
			}
			set
			{
				if ((this._CreateTime != value))
				{
					this.OnCreateTimeChanging(value);
					this.SendPropertyChanging();
					this._CreateTime = value;
					this.SendPropertyChanged("CreateTime");
					this.OnCreateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndTime
		{
			get
			{
				return this._EndTime;
			}
			set
			{
				if ((this._EndTime != value))
				{
					this.OnEndTimeChanging(value);
					this.SendPropertyChanging();
					this._EndTime = value;
					this.SendPropertyChanged("EndTime");
					this.OnEndTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LimitTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> LimitTime
		{
			get
			{
				return this._LimitTime;
			}
			set
			{
				if ((this._LimitTime != value))
				{
					this.OnLimitTimeChanging(value);
					this.SendPropertyChanging();
					this._LimitTime = value;
					this.SendPropertyChanged("LimitTime");
					this.OnLimitTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Context", DbType="NVarChar(50)")]
		public string Context
		{
			get
			{
				return this._Context;
			}
			set
			{
				if ((this._Context != value))
				{
					this.OnContextChanging(value);
					this.SendPropertyChanging();
					this._Context = value;
					this.SendPropertyChanged("Context");
					this.OnContextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reback", DbType="NVarChar(50)")]
		public string Reback
		{
			get
			{
				return this._Reback;
			}
			set
			{
				if ((this._Reback != value))
				{
					this.OnRebackChanging(value);
					this.SendPropertyChanging();
					this._Reback = value;
					this.SendPropertyChanged("Reback");
					this.OnRebackChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.taskTmpTab")]
	public partial class taskTmpTab : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TM_RID;
		
		private System.Nullable<decimal> _ID;
		
		private string _Context;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTM_RIDChanging(int value);
    partial void OnTM_RIDChanged();
    partial void OnIDChanging(System.Nullable<decimal> value);
    partial void OnIDChanged();
    partial void OnContextChanging(string value);
    partial void OnContextChanged();
    #endregion
		
		public taskTmpTab()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TM_RID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TM_RID
		{
			get
			{
				return this._TM_RID;
			}
			set
			{
				if ((this._TM_RID != value))
				{
					this.OnTM_RIDChanging(value);
					this.SendPropertyChanging();
					this._TM_RID = value;
					this.SendPropertyChanged("TM_RID");
					this.OnTM_RIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(8,0)")]
		public System.Nullable<decimal> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Context", DbType="NVarChar(50)")]
		public string Context
		{
			get
			{
				return this._Context;
			}
			set
			{
				if ((this._Context != value))
				{
					this.OnContextChanging(value);
					this.SendPropertyChanging();
					this._Context = value;
					this.SendPropertyChanged("Context");
					this.OnContextChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
